class AppError extends Error {
  constructor(message, statusCode) {
    super(message);
    this.statusCode = statusCode;
    this.status = `${statusCode}`.startsWith("4") ? "fail" : "error";
    // this will tell the app that this error is generated by app internally
    this.isOperational = true;
  }
}

module.exports = AppError;
